# Generated by Django 4.2.3 on 2024-10-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_remove_employee_bonus_remove_employee_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_id',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
    ]
