# Generated by Django 4.2.3 on 2024-10-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_alter_employee_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
